export const defaultChatStyles = {
    container: "bg-black/60 backdrop-blur-md rounded-2xl border border-white/10 shadow-2xl flex flex-col",
    header: "text-white/40 text-[10px] font-bold uppercase mb-4 border-b border-white/10 pb-2 flex items-center gap-2 tracking-widest px-4 pt-4",
    msgContainer: (isRoll: boolean) => `mx-4 p-2 rounded-xl border text-sm transition-colors ${isRoll ? 'bg-white/10 border-white/20' : 'bg-neutral-800/20 border-white/10 whitespace-pre-wrap'}`,
    user: "font-bold text-amber-500 text-[10px] uppercase tracking-widest",
    time: "text-[10px] text-white/40 font-sans",
    flavor: "text-[11px] italic text-white/50 mb-1 font-sans leading-tight",
    content: "text-center text-white/90 text-lg font-bold [&_.table-draw]:flex [&_.table-draw]:flex-col [&_.table-draw]:gap-0 [&_.table-draw]:text-left [&_.table-draw]:!m-0 [&_.table-draw]:!p-0 [&_.result-row]:flex [&_.result-row]:items-center [&_.result-row]:gap-2 [&_.result-row]:px-2 [&_.result-row]:py-1 [&_.result-row]:!mt-0 [&_.result-row]:!mb-0 [&_.result-row]:bg-white/5 [&_.result-row]:border [&_.result-row]:border-white/10 [&_.result-row:not(:first-child)]:-mt-px [&_.result-image]:w-8 [&_.result-image]:h-8 [&_.result-image]:rounded [&_.result-image]:!border-none [&_.result-image]:!m-0 [&_.result-image]:shrink-0 [&_.result-text]:text-sm [&_.result-text]:font-medium [&_.result-text]:text-white/90 [&_.chat-card]:!block [&_.chat-card]:bg-white/5 [&_.chat-card]:border [&_.chat-card]:border-white/10 [&_.chat-card]:rounded-lg [&_.chat-card]:overflow-hidden [&_.chat-card]:text-left [&_.card-header]:flex [&_.card-header]:items-center [&_.card-header]:gap-2 [&_.card-header]:bg-white/10 [&_.card-header]:px-2 [&_.card-header]:py-0.5 [&_.card-header]:border-b [&_.card-header]:border-white/10 [&_.card-header_img]:w-8 [&_.card-header_img]:h-8 [&_.card-header_img]:rounded [&_.card-header_img]:shrink-0 [&_.item-name]:text-sm [&_.item-name]:font-bold [&_.item-name]:text-white/90 [&_.item-name]:!m-0 [&_.card-content]:px-2 [&_.card-content]:py-0.5 [&_.card-content]:text-xs [&_.card-content]:text-white/70 [&_.card-content_p]:!m-0 [&_.card-footer]:hidden [&_.table-results]:flex [&_.table-results]:flex-col [&_.table-results]:gap-0 [&_.table-results]:!m-0 [&_.table-results]:!p-0 [&_.table-results]:list-none [&_.table-results_li]:flex [&_.table-results_li]:items-center [&_.table-results_li]:gap-2 [&_.table-results_li]:px-2 [&_.table-results_li]:py-1 [&_.table-results_li]:bg-white/5 [&_.table-results_li]:border [&_.table-results_li]:border-white/10 [&_.table-results_li:not(:first-child)]:-mt-px [&_.table-results_img]:w-8 [&_.table-results_img]:h-8 [&_.table-results_img]:rounded [&_.table-results_img]:shrink-0 [&_.content-link]:text-sm [&_.content-link]:text-white/90 [&_.content-link]:no-underline [&_.content-link_i]:hidden [&_.description]:text-sm [&_.description]:text-white/90",
    rollResult: "mt-1 bg-white/10 p-1.5 rounded-lg border border-white/20 text-center font-sans",
    rollFormula: "text-md text-white/40 uppercase tracking-tighter font-bold",
    rollTotal: "text-lg font-bold text-white",
    button: "inline-flex items-center gap-1 bg-white/10 hover:bg-white/20 border border-white/20 hover:border-amber-500/50 rounded-lg px-2 py-0.5 text-[10px] font-bold text-white/90 transition-all cursor-pointer my-1 shadow-sm active:scale-95",
    buttonText: "text-white/40 uppercase tracking-widest",
    buttonValue: "text-amber-500 font-bold",
    scrollButton: "bg-white/10 hover:bg-white/20 border border-white/20 hover:border-amber-500/50 rounded-lg px-3 py-1.5 text-xs font-bold text-white/90 transition-all active:scale-95",
    inputContainer: "col-span-2 flex gap-2 p-1 bg-neutral-900/50 backdrop-blur-sm rounded-lg border border-white/5 mb-2",
    inputField: "flex-1 bg-white/5 border border-white/10 rounded-md px-3 py-1.5 text-sm focus:outline-none focus:ring-1 focus:ring-amber-500/50 text-white placeholder:text-white/20",
    sendBtn: "bg-amber-600 hover:bg-amber-500 disabled:opacity-50 disabled:hover:bg-amber-600 text-black px-4 py-1.5 rounded-md text-xs font-black transition-colors"
};
