/**
 * Type declaration for the auto-generated module UI registry.
 *
 * The actual file (.managed/module-ui-registry.ts) is generated by
 * ensureManagedConfigs() before every `next dev` and `next build` run.
 * It contains one explicit import() per discovered module UI so webpack
 * can statically analyse and bundle them for production.
 *
 * This declaration file lets TypeScript type-check code that imports
 * from '@managed/module-ui-registry' without requiring the generated
 * file to exist at type-check time.
 */
declare module '@data-registry/module-ui-registry' {
    /** Loaders for local dev modules (<DATA_DIR>/local/modules/<id>/module/ui). */
    export const localModuleUIs: Record<string, () => Promise<any>>;
    /** Legacy static map for managed installs. Intentionally empty; runtime ESM handles managed UI. */
    export const dataModuleUIs: Record<string, () => Promise<any>>;
}
