import { UIModuleManifest } from './types';
import { ModuleSourceCategory } from '@shared/types/modules';
import { logger } from '@shared/utils/logger';
export * from './utils';
import React from 'react';

/**
 * Platform default manifest — always available, no file lookup required.
 * Used when no system-specific module is registered or when the system is 'generic'.
 */
const PLATFORM_DEFAULT_MANIFEST: UIModuleManifest = {
    info: {
        id: 'generic',
        title: 'Generic System',
        manifest: {
            ui: '',
            logic: '',
        },
    },
    sheet:     () => import('@client/ui/components/GenericSheet'),
    actorPage: () => import('@client/ui/pages/GenericActorPage'),
};

// Keyed by systemId. Cleared by invalidateModuleSourceCache() on source switches.
const manifestCache = new Map<string, UIModuleManifest>();

// ─── Source-aware loading ──────────────────────────────────────────────────────
//
// Module UI files are loaded via `.managed/module-ui-registry.ts`, a file that
// is auto-generated by ensureManagedConfigs() before every `next dev` / `next build`
// run. It contains ONE EXPLICIT import() per LOCAL-DEV module (TypeScript source that
// must be compiled):
//
//   localModuleUIs  — data/local/modules/<id>/module/ui (TypeScript source, bundled)
//   dataModuleUIs   — intentionally EMPTY (see below)
//
// Installed/managed modules (data/modules/<id>/dist/ui.js) are PRE-COMPILED and are NOT
// bundled into the build — they load at runtime via GET /api/modules/:id/ui (the ESM
// route with window.__SD import rewriting). This keeps a stale or malignant installed
// module out of the build graph, so it can never fail the dev/build; at runtime the
// per-module try/catch below degrades any failing module to the generic manifest.
//
// Using explicit string literals (not template literals with variables) lets webpack
// statically analyse the file and include the correct lazy chunks in the production
// bundle. Template-literal require contexts with alias arrays are NOT reliably
// resolved by webpack's scanner and produced empty chunks in production builds.
//
// When an admin switches a module's active source, the server emits a
// 'moduleSourceChanged' socket event. FoundryContext and ActorPageRouter both
// listen for this event, call invalidateModuleSourceCache(), and re-resolve —
// giving clients an in-place reload without a full page refresh.
//
// After installing or upgrading a module, a rebuild is required so the new entry
// is included in the generated registry. The RestartModal handles this flow.

// Populated lazily on first getUIModule call; reset by invalidateModuleSourceCache().
let activeSources: Record<string, string> | null = null;

function getErrorMessage(error: unknown): string {
    if (error instanceof Error) return error.message;
    if (typeof error === 'string') return error;
    return 'Unknown error';
}

function reportUIModuleLoadFailure(
    moduleId: string,
    source: string | undefined,
    message: string,
    error?: unknown,
): void {
    const errorMessage = error === undefined ? message : `${message}: ${getErrorMessage(error)}`;
    logger.warn(`[Registry] ${errorMessage}`);

    // Client-side import/evaluation failures are invisible to the server unless
    // reported back. This best-effort call updates lifecycle health for admin review.
    if (typeof fetch === 'undefined') return;
    void fetch(`/api/modules/${encodeURIComponent(moduleId)}/ui-error`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ source, message: errorMessage }),
        keepalive: true,
    }).catch(reportError => {
        logger.debug(`[Registry] Failed to report UI load failure for "${moduleId}": ${getErrorMessage(reportError)}`);
    });
}

async function fetchActiveSources(): Promise<Record<string, string>> {
    if (activeSources) return activeSources;
    try {
        const res = await fetch('/api/registry/sources');
        if (res.ok) activeSources = await res.json();
    } catch {
        // Network failure — fall back to data loaders for all modules.
    }
    return activeSources ?? {};
}

/**
 * Clears the cached active-source map and all cached manifests so the next
 * getUIModule call re-fetches from the server and reimports the module file.
 *
 * Called by:
 *  - FoundryContext on 'moduleSourceChanged' socket event (global cache bust)
 *  - ActorPageRouter on 'moduleSourceChanged' (before re-resolving its own module)
 *  - ModuleLifecycleControl after a successful switch-source API call (admin panel)
 */
export function invalidateModuleSourceCache() {
    activeSources = null;
    manifestCache.clear();

    if (typeof document !== 'undefined') {
        document.querySelectorAll('link[data-module]').forEach(el => el.remove());
    }
}

/**
 * JIT UI Manifest Loader (Browser-Safe)
 *
 * Resolves the UIModuleManifest for a system by consulting the server's active-source
 * map (GET /api/registry/sources) and then looking up the module in the pre-generated
 * registry (.managed/module-ui-registry.ts).
 *
 *   ModuleSourceCategory.Local   → localModuleUIs[id]   (data/local/modules, bundled source)
 *   ModuleSourceCategory.Managed → runtime ESM route    (data/modules, pre-compiled artifact)
 *   ModuleSourceCategory.BuiltIn → runtime ESM route    (no built-in UI modules currently)
 *
 * `dataModuleUIs` is always empty (installed modules are not bundled); managed installs
 * fall through to the runtime ESM route below. Falls back to PLATFORM_DEFAULT_MANIFEST
 * when the module is not resolvable or when its loader throws — a failing module never
 * crashes the platform.
 */
export async function getUIModule(systemId: string): Promise<UIModuleManifest> {
    const id = systemId.toLowerCase();

    if (id === 'generic') return PLATFORM_DEFAULT_MANIFEST;

    if (manifestCache.has(id)) return manifestCache.get(id)!;

    const sources = await fetchActiveSources();
    const source = sources[id];

    let manifest: UIModuleManifest = PLATFORM_DEFAULT_MANIFEST;

    // Dynamically import the registry — it is a generated file so we import it
    // lazily to ensure we always get the version that was built into the bundle.
    const { localModuleUIs, dataModuleUIs } = await import('@data-registry/module-ui-registry');


    // Local dev source takes priority when the server has it marked active.
    if (source === ModuleSourceCategory.Local) {
        const loader = localModuleUIs[id];
        if (loader) {
            try {
                const m = await loader();
                manifest = m.default || m;
            } catch (e) {
                reportUIModuleLoadFailure(id, ModuleSourceCategory.Local, `Failed to load local UI manifest for "${id}"`, e);
                // Fall through to data loaders below.
            }
        }
    }

    // Legacy static map for installed modules — now always empty (installed modules are
    // not bundled). Retained for the import shape; managed installs fall through to the
    // runtime ESM route below.
    if (manifest === PLATFORM_DEFAULT_MANIFEST) {
        const loader = dataModuleUIs[id];
        if (loader) {
            try {
                const m = await loader();
                manifest = m.default || m;
            } catch (e) {
                reportUIModuleLoadFailure(id, ModuleSourceCategory.Managed, `Failed to load data UI manifest for "${id}"`, e);
            }
        }
    }

    // Module not in the static registry — it was installed at runtime after the
    // Next.js build. Load via the platform API which serves the artifact with bare
    // ESM imports rewritten to window.__SD.* globals so the browser can execute it.
    // webpackIgnore tells webpack not to attempt static analysis of this import.
    // compiledStyles lives on the packager-patched artifact info.json, not the source
    // info.json bundled into ui.js — so the runtime UI route re-exports it (decision 37).
    let routeCompiledStyles: string | undefined;
    if (manifest === PLATFORM_DEFAULT_MANIFEST) {
        try {
            const m = await import(/* webpackIgnore: true */ `/api/modules/${id}/ui`);
            manifest = m.default || m;
            if (typeof (m as { __sdCompiledStyles?: unknown }).__sdCompiledStyles === 'string') {
                routeCompiledStyles = (m as { __sdCompiledStyles?: string }).__sdCompiledStyles;
            }
        } catch (e) {
            reportUIModuleLoadFailure(id, source ?? ModuleSourceCategory.Managed, `Failed to load runtime UI manifest for "${id}"`, e);
        }
    }

    if (manifest === PLATFORM_DEFAULT_MANIFEST) {
        const message = `No UI manifest found for "${id}" (source: ${source ?? 'unknown'})`;
        if (source) reportUIModuleLoadFailure(id, source, message);
        else logger.warn(`[Registry] ${message}`);
    }

    manifestCache.set(id, manifest);

    // Inject module stylesheet(s). The package-time compiled Tailwind artifact (if the
    // packager produced one — `info.compiledStyles`, ADR-0027 decision 37) is linked FIRST
    // so author CSS declared via `stylesheet` (string | string[], decision 36) can override
    // utilities. Each entry is a separate <link>, deduped per href — they compose via the
    // cascade under `.sdk-module--<id>`, never merged.
    if (typeof document !== 'undefined') {
        const injectStylesheet = (relPath: string) => {
            const sheetPath = relPath.replace(/^\/?assets\//, '');
            const href = `/api/modules/${id}/assets/${sheetPath}`;
            if (document.querySelector(`link[rel="stylesheet"][href="${href}"]`)) return;
            const link = document.createElement('link');
            link.rel = 'stylesheet';
            link.href = href;
            link.dataset.module = id;
            document.head.appendChild(link);
        };

        const compiledStyles = manifest.info?.compiledStyles ?? routeCompiledStyles;
        if (compiledStyles) injectStylesheet(compiledStyles);

        const declared = manifest.stylesheet;
        const sheets = Array.isArray(declared) ? declared : declared ? [declared] : [];
        for (const sheet of sheets) injectStylesheet(sheet);
    }

    return manifest;
}
