import { UIModuleManifest } from './types';
export * from './utils';
import React from 'react';

/**
 * Platform default manifest — always available, no file lookup required.
 * Used when no system-specific module is registered or when the system is 'generic'.
 */
const PLATFORM_DEFAULT_MANIFEST: UIModuleManifest = {
    info: { id: 'generic', title: 'Generic System' },
    sheet:     () => import('@client/ui/components/GenericSheet'),
    actorPage: () => import('@client/ui/pages/GenericActorPage'),
};

// Keyed by systemId. Cleared by invalidateModuleSourceCache() on source switches.
const manifestCache = new Map<string, UIModuleManifest>();

// ─── Source-aware loading ──────────────────────────────────────────────────────
//
// Module UI files are loaded via `.managed/module-ui-registry.ts`, a file that
// is auto-generated by ensureManagedConfigs() before every `next dev` / `next build`
// run. It contains ONE EXPLICIT import() per discovered module, keyed by module id
// and split into two maps — one for local dev source, one for managed installs:
//
//   localModuleUIs  — data/local/modules/<id>/module/ui (TypeScript source)
//   dataModuleUIs   — data/modules/<id>/dist/ui         (compiled artifact)
//
// Using explicit string literals (not template literals with variables) lets webpack
// statically analyse the file and include the correct lazy chunks in the production
// bundle. Template-literal require contexts with alias arrays are NOT reliably
// resolved by webpack's scanner and produced empty chunks in production builds.
//
// When an admin switches a module's active source, the server emits a
// 'moduleSourceChanged' socket event. FoundryContext and ActorPageRouter both
// listen for this event, call invalidateModuleSourceCache(), and re-resolve —
// giving clients an in-place reload without a full page refresh.
//
// After installing or upgrading a module, a rebuild is required so the new entry
// is included in the generated registry. The RestartModal handles this flow.

// Populated lazily on first getUIModule call; reset by invalidateModuleSourceCache().
let activeSources: Record<string, string> | null = null;

async function fetchActiveSources(): Promise<Record<string, string>> {
    if (activeSources) return activeSources;
    try {
        const res = await fetch('/api/registry/sources');
        if (res.ok) activeSources = await res.json();
    } catch {
        // Network failure — fall back to data loaders for all modules.
    }
    return activeSources ?? {};
}

/**
 * Clears the cached active-source map and all cached manifests so the next
 * getUIModule call re-fetches from the server and reimports the module file.
 *
 * Called by:
 *  - FoundryContext on 'moduleSourceChanged' socket event (global cache bust)
 *  - ActorPageRouter on 'moduleSourceChanged' (before re-resolving its own module)
 *  - ModuleLifecycleControl after a successful switch-source API call (admin panel)
 */
export function invalidateModuleSourceCache() {
    activeSources = null;
    manifestCache.clear();

    if (typeof document !== 'undefined') {
        document.querySelectorAll('link[data-module]').forEach(el => el.remove());
    }
}

/**
 * JIT UI Manifest Loader (Browser-Safe)
 *
 * Resolves the UIModuleManifest for a system by consulting the server's active-source
 * map (GET /api/registry/sources) and then looking up the module in the pre-generated
 * registry (.managed/module-ui-registry.ts).
 *
 *   'local'    → localModuleUIs[id]  (data/local/modules, TypeScript source)
 *   'data'     → dataModuleUIs[id]   (data/modules, compiled artifact)
 *   'built-in' → dataModuleUIs[id]   (falls back — no built-in UI modules currently)
 *
 * Falls back to PLATFORM_DEFAULT_MANIFEST when the module is not in the registry
 * or when its loader throws.
 */
export async function getUIModule(systemId: string): Promise<UIModuleManifest> {
    const id = systemId.toLowerCase();

    if (id === 'generic') return PLATFORM_DEFAULT_MANIFEST;

    if (manifestCache.has(id)) return manifestCache.get(id)!;

    const sources = await fetchActiveSources();
    const source = sources[id];

    let manifest: UIModuleManifest = PLATFORM_DEFAULT_MANIFEST;

    // Dynamically import the registry — it is a generated file so we import it
    // lazily to ensure we always get the version that was built into the bundle.
    const { localModuleUIs, dataModuleUIs } = await import('@data-registry/module-ui-registry');

    // Local dev source takes priority when the server has it marked active.
    if (source === 'local') {
        const loader = localModuleUIs[id];
        if (loader) {
            try {
                const m = await loader();
                manifest = m.default || m;
            } catch (e) {
                console.warn(`[Registry] Failed to load local UI manifest for "${id}":`, e);
                // Fall through to data loaders below.
            }
        }
    }

    // Managed install or built-in — use the data registry.
    if (manifest === PLATFORM_DEFAULT_MANIFEST) {
        const loader = dataModuleUIs[id];
        if (loader) {
            try {
                const m = await loader();
                manifest = m.default || m;
            } catch (e) {
                console.warn(`[Registry] Failed to load data UI manifest for "${id}":`, e);
            }
        }
    }

    // Module not in the static registry — it was installed at runtime after the
    // Next.js build. Load via the platform API which serves the artifact with bare
    // ESM imports rewritten to window.__SD.* globals so the browser can execute it.
    // webpackIgnore tells webpack not to attempt static analysis of this import.
    if (manifest === PLATFORM_DEFAULT_MANIFEST) {
        try {
            const m = await import(/* webpackIgnore: true */ `/api/modules/${id}/ui`);
            manifest = m.default || m;
        } catch (e) {
            console.warn(`[Registry] Failed to load runtime UI manifest for "${id}":`, e);
        }
    }

    if (manifest === PLATFORM_DEFAULT_MANIFEST) {
        console.warn(`[Registry] No UI manifest found for "${id}" (source: ${source ?? 'unknown'})`);
    }

    manifestCache.set(id, manifest);

    // Inject module stylesheet if declared
    if (manifest.stylesheet && typeof document !== 'undefined') {
        const href = `/api/modules/${id}/assets/${manifest.stylesheet}`;
        const existing = document.querySelector(`link[data-module="${id}"]`);
        if (!existing) {
            const link = document.createElement('link');
            link.rel = 'stylesheet';
            link.href = href;
            link.dataset.module = id;
            document.head.appendChild(link);
        }
    }

    return manifest;
}
